apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: falcosidekick
  namespace: falcosidekick
  annotations:
    kubernetes.io/ingress.class: "nginx"
  labels:
    app.kubernetes.io/name: falcosidekick
    app.kubernetes.io/part-of: falco
spec:
  tls:
  - hosts:
    - falco
    - www.wishin.app
    secretName: falcosidekick-tls
  rules:
  - host: "falcosidekick.home.pulsifer.ca"
    http:
      paths:
      - path: /
        backend:
          serviceName: falcosidekick
          servicePort: 2801
  backend:
    serviceName: falcosidekick
    servicePort: 2801
