apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: falcosidekick
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  defaultAllowPrivilegeEscalation: false
  allowPrivilegeEscalation: false
  allowedUnsafeSysctls: []
  allowedCapabilities: []
  requiredDropCapabilities:
  - ALL
  hostNetwork: false
  hostIPC: false
  hostPID: false
  fsGroup:
    ranges:
    - max: 1234
      min: 1234
    rule: MustRunAs
  runAsUser:
    rule: MustRunAs
    ranges:
    - max: 1234
      min: 1234
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - configMap
  - secret
