apiVersion: v1
kind: Namespace
metadata:
  name: falco
  labels:
    app.kubernetes.io/name: falco
    app.kubernetes.io/part-of: falco

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allowed-psps
  namespace: falco
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['falco']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allowed-psps
  namespace: falco
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allowed-psps
subjects:
- kind: ServiceAccount
  name: falco
  namespace: falco

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: falco
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
