apiVersion: v1
kind: ServiceAccount
metadata:
  name: lab
  namespace: lab
  labels:
    app.kubernetes.io/name: lab
    app.kubernetes.io/part-of: lab
  annotations:
    iam.gke.io/gcp-service-account: cloudlab@kubesec.iam.gserviceaccount.com
---
