apiVersion: v1
kind: ConfigMap
metadata:
  name: datadogtoken
  namespace: kube-public
  labels:
    app: datadog
data:
  event.tokenKey: "0"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: datadog-config
  namespace: kube-public
  labels:
    app: datadog
data:
