steps:
# fetch cluster credentials
- name: 'gcr.io/cloud-builders/gcloud'
  id: get-config
  args: ['container', 'clusters', 'get-credentials', '${_CLUSTER_NAME}']
  env:
  - 'KUBECONFIG=kubeconfig.yml'
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  - 'CLOUDSDK_CORE_PROJECT=${_CLUSTER_PROJECT}'

# fix auth-provider
- name: 'gcr.io/cloud-builders/kubectl'
  id: fix-config-pre
  waitFor: ['get-config']
  args: ['config', 'unset', 'users.gke_${_CLUSTER_PROJECT}_${_CLUSTER_ZONE}_${_CLUSTER_NAME}.auth-provider']
  env: ['KUBECONFIG=kubeconfig.yml']
  env:
  - 'KUBECONFIG=kubeconfig.yml'
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  - 'CLOUDSDK_CORE_PROJECT=${_CLUSTER_PROJECT}'

- name: 'gcr.io/cloud-builders/kubectl'
  id: fix-config
  waitFor: ['fix-config-pre']
  args: ['config', 'set-credentials', 'gke_${_CLUSTER_PROJECT}_${_CLUSTER_ZONE}_${_CLUSTER_NAME}', '--auth-provider=gcp']
  env: ['KUBECONFIG=kubeconfig.yml']
  env:
  - 'KUBECONFIG=kubeconfig.yml'
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  - 'CLOUDSDK_CORE_PROJECT=${_CLUSTER_PROJECT}'


# copy kubeconfig into GCS
- name: 'gcr.io/cloud-builders/gsutil'
  id: copy-config
  waitFor: ['fix-config']
  args: ['cp', 'kubeconfig.yml', 'gs://cloud-lab']

# pre-pull kubernetes-deploy-image
- name: 'gcr.io/cloud-builders/docker'
  id: k8s-deploy-image
  waitFor: ['-']
  args: ['pull', 'gcr.io/trusted-builds/kubernetes-deploy']

# kubernetes-deploy the thing
- name: 'gcr.io/trusted-builds/kubernetes-deploy'
  args: ['kubernetes-deploy', 'lab', 'gke_${_CLUSTER_PROJECT}_${_CLUSTER_ZONE}_${_CLUSTER_NAME}']
  waitFor: ['k8s-deploy-image', 'fix-config']
  env:
  - 'KUBECONFIG=kubeconfig.yml'
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  - 'CLOUDSDK_CORE_PROJECT=${_CLUSTER_PROJECT}'
  - 'ENVIRONMENT=${_ENVIRONMENT}'
  - 'REVISION=${_REVISION}'

# kubernetes-deploy the lab namespace
- name: 'gcr.io/trusted-builds/kubernetes-deploy'
  args: ['kubernetes-deploy', 'lab', 'gke_${_CLUSTER_PROJECT}_${_CLUSTER_ZONE}_${_CLUSTER_NAME}', '--template-dir=k8s/namespaces/lab']
  waitFor: ['k8s-deploy-image', 'fix-config']
  env:
  - 'KUBECONFIG=kubeconfig.yml'
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  - 'CLOUDSDK_CORE_PROJECT=${_CLUSTER_PROJECT}'
  - 'ENVIRONMENT=${_ENVIRONMENT}'
  - 'REVISION=${_REVISION}'

# fill in the blanks
substitutions:
  _CLUSTER_NAME: cloudlab
  _CLUSTER_ZONE: us-east4-b
  _CLUSTER_PROJECT: kubesec
  _REVISION: lol
  _ENVIRONMENT: production
