apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  annotations:
    # cloud.google.com/app-protocols: '{"api":"HTTPS","cluster":"HTTPS"}'
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: vault
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 8200
      protocol: TCP
    - name: cluster
      port: 8201
      protocol: TCP
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: vault
