apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vault
  namespace: vault
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    external-dns.alpha.kubernetes.io/ttl: "60"
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: vault
spec:
  tls:
  - hosts:
    - vault.home.pulsifer.ca
    secretName: vault.home.pulsifer.ca
  rules:
  - host: vault.home.pulsifer.ca
    http:
      paths:
      - backend:
          serviceName: vault
          servicePort: 8200
        path: "/*"
      - backend:
          serviceName: vault
          servicePort: 8200
        path: "/v1/*"
  backend:
    serviceName: vault
    servicePort: 8200
