apiVersion: v1
kind: Namespace
metadata:
  name: outline
  labels:
    app.kubernetes.io/name: outline
    app.kubernetes.io/part-of: outline

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allowed-psps
  namespace: outline
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['outline']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allowed-psps
  namespace: outline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allowed-psps
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: outline
  namespace: outline

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: outline
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
