apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: bullseye-k8s-lolwtf-ca
  namespace: bullseye
  labels:
    app.kubernetes.io/name: bullseye
    app.kubernetes.io/part-of: bullseye
spec:
  secretName: bullseye-k8s-lolwtf-ca-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: bullseye.k8s.lolwtf.ca
  dnsNames:
  - bullseye.k8s.lolwtf.ca
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - bullseye.k8s.lolwtf.ca
    - http01:
        ingress: bullseye-k8s-lolwtf-ca
      domains:
      - bullseye.k8s.lolwtf.ca
