apiVersion: v1
kind: Namespace
metadata:
  name: covidshield
  labels:
    app.kubernetes.io/name: covidshield
    app.kubernetes.io/part-of: covidshield

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allowed-psps
  namespace: covidshield
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['covidshield']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allowed-psps
  namespace: covidshield
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allowed-psps
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: covidshield
  namespace: covidshield

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: covidshield
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
