apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-submission
  namespace: covidshield
  labels:
    app.kubernetes.io/name: key-submission
    app.kubernetes.io/part-of: covidshield
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: key-submission
      app.kubernetes.io/part-of: covidshield
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: key-submission
        app.kubernetes.io/part-of: covidshield
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: key-submission
        image: jonpulsifer/key-submission:latest
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "covidshield:covidshield@tcp(mysql.mysql)/covidshield"
        - name: KEY_CLAIM_TOKEN
          value: test=ON
        ports:
        - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-retrieval
  namespace: covidshield
  labels:
    app.kubernetes.io/name: key-retrieval
    app.kubernetes.io/part-of: covidshield
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: key-retrieval
      app.kubernetes.io/part-of: covidshield
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: key-retrieval
        app.kubernetes.io/part-of: covidshield
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: key-submission
        image: jonpulsifer/key-retrieval:latest
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "covidshield:covidshield@tcp(mysql.mysql)/covidshield"
        - name: RETRIEVE_HMAC_KEY
          value: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        ports:
        - containerPort: 8001