apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    certmanager.k8s.io/disable-validation: "true"
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allowed-psps
  namespace: cert-manager
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['cert-manager']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allowed-psps
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allowed-psps
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: cert-manager
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: cert-manager
    namespace: cert-manager
  spec:
    podSelector:
      matchLabels:
        app.kubernetes.io: cert-manager
    policyTypes:
    - Egress
    egress:
    - to:
      - ipBlock:
          cidr: 10.10.0.1/32
      ports:
        - protocol: TCP
          port: 443
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
          except: [ 10.0.0.0/8 ]
