apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
  namespace: cert-manager
spec:
  acme:
    email: jonathan@pulsifer.ca
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-issuer
    solvers:
    - selector: {}
      dns01:
        clouddns:
          project: kubesec
          serviceAccountSecretRef:
            name: gcp-sa
            key: credentials.json
    - selector:
        dnsNames:
        - wishin.app
        - www.wishin.app
        - '*.wishin.app'
      dns01:
        clouddns:
          project: wishlist-4362e
          serviceAccountSecretRef:
            name: gcp-sa
            key: credentials.json
