apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
  namespace: cert-manager
spec:
  acme:
    email: jonathan@pulsifer.ca
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-issuer
    solvers:
    - selector: {}
      dns01:
        clouddns:
          project: homelab-ng
          serviceAccountSecretRef:
            name: gcp-service-account
            key: credentials.json
