apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
  namespace: cert-manager
spec:
  acme:
    email: jonathan@pulsifer.ca
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-issuer
    dns01:
      providers:
      - name: letsencrypt-dns
        clouddns:
          project: kubesec
          serviceAccountSecretRef:
            name: gcp-service-account
            key: credentials.json
