# Fluentd ports
- macro: fluentd_http_port
  condition: fd.sport=9880
- macro: fluentd_forward_port
  condition: fd.sport=24224

# - rule: Fluentd unexpected network inbound traffic
#   desc: inbound network traffic to fluentd on a port other than the standard ports
#   condition: user.name = td-agent and inbound and not (fluentd_forward_port or fluentd_http_port)
#   output: "Inbound network traffic to Fluentd on unexpected port (connection=%fd.name)"
#   priority: WARNING

# - rule: Tdagent unexpected network outbound traffic
#   desc: outbound network traffic from fluentd on a port other than the standard ports
#   condition: user.name = td-agent and outbound and not fluentd_forward_port
#   output: "Outbound network traffic from Fluentd on unexpected port (connection=%fd.name)"
#   priority: WARNING

- rule: Mysql unexpected network inbound traffic
  desc: inbound network traffic to mysql on a port other than the standard ports
  condition: user.name = mysql and inbound and fd.sport != 3306
  output: "Inbound network traffic to MySQL on unexpected port (connection=%fd.name)"
  priority: WARNING

- rule: HTTP server unexpected network inbound traffic
  desc: inbound network traffic to a http server program on a port other than the standard ports
  condition: proc.name in (http_server_binaries) and inbound and fd.sport != 80 and fd.sport != 443
  output: "Inbound network traffic to HTTP Server on unexpected port (connection=%fd.name)"
  priority: WARNING
