apiVersion: v1
kind: ServiceAccount
metadata:
  name: thehive
  namespace: thehive
  labels:
    app.kubernetes.io/name: thehive
    app.kubernetes.io/part-of: thehive
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cortex
  namespace: thehive
  labels:
    app.kubernetes.io/name: cortex
    app.kubernetes.io/part-of: thehive
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:thehive
  namespace: thehive
  labels:
    app.kubernetes.io/name: thehive
    app.kubernetes.io/part-of: thehive
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['thehive']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:thehive
  namespace: thehive
  labels:
    app.kubernetes.io/name: thehive
    app.kubernetes.io/part-of: thehive
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:thehive
subjects:
- kind: ServiceAccount
  name: thehive
  namespace: thehive
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:cortex
  namespace: thehive
  labels:
    app.kubernetes.io/name: cortex
    app.kubernetes.io/part-of: thehive
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['cortex']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:cortex
  namespace: thehive
  labels:
    app.kubernetes.io/name: cortex
    app.kubernetes.io/part-of: thehive
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:cortex
subjects:
- kind: ServiceAccount
  name: cortex
  namespace: thehive
