apiVersion: v1
kind: Secret
metadata:
  name: thehive-cortex
  namespace: thehive
  labels:
    app.kubernetes.io/name: thehive
    app.kubernetes.io/part-of: thehive
type: Opaque
data:
  cortex.conf: Y29ydGV4IHsKICBzZXJ2ZXJzOiBbCiAgICB7CiAgICAgIG5hbWU6ICJjb3J0ZXgiCiAgICAgIHVybDogImh0dHA6Ly9jb3J0ZXg6OTAwMSIKICAgICAgYXV0aCB7CiAgICAgICAgdHlwZTogImJlYXJlciIKICAgICAgICBrZXk6ICI1NFZBSXY3a0VINkQxendmV1FtWm5wc0M1MmYzZll2WCIKICAgICAgfQogICAgICB3c0NvbmZpZyB7fQogICAgfQogIF0KfQo=
