apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: home-pulsifer-ca
  namespace: nginx
  labels:
    app.kubernetes.io/name: home-pulsifer-ca
    app.kubernetes.io/part-of: nginx
spec:
  secretName: home-pulsifer-ca-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: home.pulsifer.ca
  dnsNames:
  - home.pulsifer.ca
