---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx
  labels:
    app: nginx
data:
  hsts-preload: "true"
  hsts-max-age: "31536000"
  proxy-set-headers: "nginx/nginx-headers"
  use-gzip: "true"
  use-proxy-protocol: "false"
  log-format-upstream: '{ "time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr",
    "x-forward-for": "$proxy_add_x_forwarded_for", "request_id": "$request_id", "remote_user":
    "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status":
    $status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri",
    "request_query": "$args", "request_length": $request_length, "duration": $request_time,
    "method": "$request_method", "http_referrer": "$http_referer", "http_user_agent":
    "$http_user_agent" }'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-udp
  namespace: nginx
  labels:
    app: nginx
data:
  # 53: "sinkhole/sinkhole:53"
  # 5060: "asterisk/asterisk:5060"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-tcp
  namespace: nginx
  labels:
    app: nginx
data:
  # 53: "sinkhole/sinkhole:53"
  8200: "vault/vault:8200"
  # 10022: "bullseye/ssh:22"
  # 8443: "fleet/fleet:443"
  # 25565: "minecraft/minecraft:25565"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-headers
  namespace: nginx
  labels:
    app: nginx
data:
  X-Request-Start: t=${msec}
  X-cloud: gke
