apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/part-of: oauth2-proxy
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/part-of: oauth2-proxy
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  resourceNames: ["oauth2-proxy"]
  verbs: ["get"]
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
  resourceNames: ["oauth2-proxy"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/part-of: oauth2-proxy
subjects:
- kind: ServiceAccount
  name: oauth2-proxy
  namespace: oauth2-proxy
roleRef:
  kind: ClusterRole
  name: oauth2-proxy
  apiGroup: rbac.authorization.k8s.io
