apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: auth.pulsifer.ca
  namespace: oauth2-proxy
  labels:
    app.kubernetes.io/name: auth.pulsifer.ca
    app.kubernetes.io/part-of: oauth2-proxy
spec:
  secretName: auth.pulsifer.ca
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  commonName: auth.pulsifer.ca
  dnsNames:
  - auth.pulsifer.ca
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: auth.home.pulsifer.ca
  namespace: oauth2-proxy
  labels:
    app.kubernetes.io/name: auth.home.pulsifer.ca
    app.kubernetes.io/part-of: oauth2-proxy
spec:
  secretName: auth.home.pulsifer.ca
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: auth.home.pulsifer.ca
  dnsNames:
  - auth.home.pulsifer.ca
