apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/part-of: oauth2-proxy
spec:
  secretName: oauth2-proxy-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: oauth2-proxy.home.pulsifer.ca
  dnsNames:
  - oauth2-proxy.home.pulsifer.ca
