apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/part-of: oauth2-proxy
type: Opaque
data:
  client-id: "629296473058-g6i3mt60i4t3sckpiru52d92gat6tqk4.apps.googleusercontent.com"
  client-secret: ""
